name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version to release: major, minor or patch'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run release script
        run: bash release.sh ${{ inputs.version }}