name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version to release: major, minor or patch'
        required: true
        default: ['major', 'minor', 'patch']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        
      - name: Configure git identity
        run: |
          git config --global user.email "christian_nogueras94@hotmail.com"
          git config --global user.name "Christian Nogueras"

      - name: Run release script
        run: bash release.sh ${{ inputs.version }}